ckanext/bcgov/commands/edc_commands.py, ckanext/bcgov/controllers/package.py, ckanext/bcgov/forms/dataset_form.py, ckanext/bcgov/templates/package/resource_read.html, pip-requirements.txt
This PR addresses code changes for migrating the catalogue to CKAN 2.3. In addition, a few other things need to happen for a successful migration:
- Run database migration for 2.3. This can be done with `paster db upgrade’
- `pdf_preview` extension no longer exists. Need to install https://github.com/ckan/ckanext-pdfview.git
- CKAN 2.3. uses the new ResourceView feature instead of resource previews. For geographic views, this extension needs to be installed: https://github.com/pduchesne/ckanext-geoview
- There is a new schema version for CKAN 2.3. This can be retrieved from the CKAN source here: https://github.com/ckan/ckan/blob/ckan-2.3/ckan/config/solr/schema.xml.
- Because of the new schema, clean the existing index, restart SOLR, and reindex everything.
- …
=> Migration to CKAN 2.3

ckanext/bcgov/util/helpers.py
This reverts commit 1cd470bcd7e2062b82b1ffa55b4d94fd454dd246.
Turns out it wasn't faster. Note to self: always measure.
=> Revert "get_organization_title faster"

ckanext/bcgov/templates/package/comments_block.html
The old links in disqus comments section are hard coded to http protocol. Downloading those files in an https protocol will issue mixed content errors, and pose security danger.
Instead of hardcoding to either http or https, '//' makes the url protocol-relative, which means the link will choose to use the protocol of the site.
=> change urls in disqus to protocol-relative

ckanext/bcgov/fanstatic/edc-file-upload.js, ckanext/bcgov/templates/macros/form.html, ckanext/bcgov/templates/package/snippets/resource_form.html
This pull request fixes the problem discussed in [File Upload UX issue #2604](https://github.com/ckan/ckan/issues/2604#issuecomment-136771673).
Field name 'URL is changed to 'File'.
The small red 'X' button is replaced by a big 'Remove' button. As this part of form imports the CKAN form macro directly (which we obviously can't change right now), I created our own form macro by copying the one in CKAN, except that it references a new 'edc-file-upload.js' file, which has the UX we want.
=> Resource upload form fieldname and reset button

ckanext/bcgov/templates/package/edc_type_form.html, ckanext/bcgov/templates/package/search.html, ckanext/bcgov/templates/package/snippets/request_data.html, ckanext/bcgov/templates/package/snippets/rss_feeds.html, ckanext/bcgov/templates/snippets/facet_list.html, ckanext/bcgov/templates/snippets/search_form.html
IDs have been added to the elements listed below:
//*[@id="content"]/div[3]/aside
https://cat.data.gov.bc.ca/dataset
On the homepage of the catalogue on the left hand side is a column with all the available search filters. I would like an id for this entire panel.
id = "filters-panel"
//*[@id="content"]/div[3]/aside/section[x] (x is between 1 and 7 inclusively.)
https://cat.data.gov.bc.ca/dataset
I would also like id's for each category of filter, i.e. License, Sectors, Dataset types,...(there's 7 excluding Request Data))
id = "licence-filter, sectors-filter, dataset-types-filter..."
The eighth one is "Request data", if that could just be called "request-data" that would be great.
//*[@id="form-dataset-search"]/div[2]/div[1]/h2
https://cat.data.gov.bc.ca/datasets
Another one for the …
=> CITZEDC573 - Added IDs to elements for selenium

ckanext/bcgov/templates/package/snippets/security_classification.html
and field removal
Fixed the text for Application records in Access & Security to read 'Who
can access this application?'
Removed 'Who can download this dataset?' for Application records in
Access & Security
=> CITZEDC-525 - Application record template label update

ckanext/bcgov/fanstatic/edc_theme.css, ckanext/bcgov/templates/header.html, ckanext/bcgov/templates/snippets/mobile-main-navigation.html
Changes:
- only using the image with 'British Columbia' text for both mobile
and regular view
- 'DataBC' text in header changed to 'Data Catalogue'
- In mobile view, breadcumb is now hidden
- In mobile view, 'Data Catalogue' text moves out of the header and is
displayed below the header
- In mobile view, links in the navigation ribbon have are displayed in
the hamburger menu instead of the main view
=> CITZEDC-854 - Modifications needed for header

ckanext/bcgov/templates/package/snippets/additional_info.html, ckanext/bcgov/templates/package/snippets/pkg_extra_info.html
Data Quality and Lineage Statements are always visible on Geographic and Dataset. Also Data and Lineage are remove from pkg_extra_info template and won't show on Application and Service package types.
=> Issue #176 empty data lineage

ckanext/bcgov/templates/organization/members.html
Need the breadcrumb for org/member page to display 'Members'
Issue #217
=> Fixing breadcrumb for org/members page

ckanext/bcgov/controllers/ofi.py, ckanext/bcgov/fanstatic/edc_mow.js, ckanext/bcgov/fanstatic/edc_mow_style.css, ckanext/bcgov/logic/auth/ofi/call_action.py, ckanext/bcgov/logic/ofi/call_action.py, ckanext/bcgov/plugin.py, ckanext/bcgov/templates/snippets/edc_mow.html
mow now requires email and consent
ofi manage edit ofi resources should be working again
create_aoi refactored to ofi_create_order
=> Reverting back to format name instead of id for resource metadata, plus other fixes

ckanext/bcgov/logic/auth/ofi/call_action.py
Issue #300 
file_formats action now allows for authorizing anonymous users to make the /info/fileFormats DWDS api call through bcgov ckan
=> Issue 300 - Fixing access denied error for users placing an order

ckanext/bcgov/controllers/ofi.py, ckanext/bcgov/controllers/package.py, ckanext/bcgov/fanstatic/edc_mow.js, ckanext/bcgov/fanstatic/ofi/ofi_modal.js, ckanext/bcgov/logic/ofi/__init__.py, ckanext/bcgov/logic/ofi/call_action.py, ckanext/bcgov/templates/ofi/ofi_modal.html
Issues #311 #312 
WIP, needs some testing cad.
This PR include several changes that ended up crossing between the 2 tickets. 
First off, `populate_dataset_with_ofi` action function had some issues with api calls, but should now be in a state for bulk update. `/api/action` or `/api/ofi` urls can be used to `POST` to `populate_dataset_with_ofi`. There is one caveat to using the `/api/ofi` endpoint; You must include `Accept: application/json` in your request header to get a usable response, otherwise html will be in the response body.
`populate_dataset_with_ofi` can now deal with no object name set in the dataset. This PR also includes front-end changes to accommodate for no set object name.
When trying to `populate_dataset_with_ofi` via api on a dataset with no object name, `force_populate` …
=> Issue #311 & #312 - Updating populate_dataset_with_ofi for bulk update use

ckanext/bcgov/controllers/package.py, ckanext/bcgov/plugin.py, ckanext/bcgov/templates/ofi/ofi_modal.html, ckanext/bcgov/templates/package/snippets/package_form.html, ckanext/bcgov/templates/package/snippets/resource_form.html
Issue #312 
This PR had to include overriding ckan's route for creating a new dataset. Extensive testing should be done with all dataset types. 
The behaviour should be exactly the same when creating a dataset.
The only difference is that clicking on the 'Save Dataset' button should redirect to the new dataset read page if successful. 
Any errors that may occur when submitting by the 'Save Dataset' or 'Next: Add Data' buttons, should also be the same as before.
=> Issue #312 - Save Dataset without adding resources

ckanext/bcgov/templates/package/snippets/additional_info.html
Part of the ckanext was not calling render_markdown() so markdown was not being rendered in the **Purpose** section
=> fix markdown rendering

ckanext/bcgov/util/helpers.py
Quick fix to remove the `(external link)` text from listing of OFI resources.
=> removed "external link" from resource list details

ckanext/bcgov/fanstatic/edc_mow.js, ckanext/bcgov/logic/ofi/call_action.py
If a user is zoomed all the way out of the map in the modal, and then places an order, aoiType is specified to be non-spatial and no aoi document of coordinates are sent for the order.
=> Issue #313 - Sent aoiType for non-spatial province-wide orders

ckanext/bcgov/templates/package/resource_read.html
Issue #336 
In templates, only render the resource preview if datastore is enabled on the resource or isn't external.
=> Issue #336 - stop external non-datastore previews from displaying

ckanext/bcgov/controllers/api.py
Fixing a bug I found last week.  organizations parameter never worked.  I couldn't find any examples illustrating the correct syntax to use.  This works.
=> parse string of list of strings into list of strings

ckanext/bcgov/plugin.py
Filter queries can use `OR` or `AND` as the default operator.
This sets the default to `AND` so that expressions such as:
```
fq=res_format:"pdf" license_id:"2" sector:"Health and Safety" +(edc_state:("PUBLISHED"+OR+"PENDING+ARCHIVE") AND metadata_visibility:("Public"))
```
each filter will be `AND'd`  Else they will be `OR'd`
=> A better solution to the Filter Query issue

ckanext/bcgov/templates/package/read.html, ckanext/bcgov/templates/snippets/package_item.html
#403  Using mockup on the dataset pages, commented out the tracking info on the dataset list pages
=> 403 - Showing tracking count on datasets

ckanext/bcgov/templates/snippets/search_form.html
#450 
font-awesome said the fa-remove would be an alias, but i guess it doesn't work, so changed to fa-times
=> #450 - Fixed icon for facet pills

ckanext/bcgov/forms/edc_datasets.py
#501
Can't use `not_empty` on resource_storage_location currently because when adding or updating resources, if that field is missing from other resources in the dataset, then the new or edited resource fails.
=> #501 - Revert resource_storage_location validator

ckanext/bcgov/fanstatic/edc_pow.js
This is to fix the Issue with Mapsheet aoi calculation when ordering using the POW via BCDC.
'aoi' was missing from the JSON which submits the order.
=> add 'aoi' to order to fix bug

README.md, ckanext/bcgov/fanstatic/edc_pow.js, ckanext/bcgov/templates/package/resource_read.html
Passing empty values to the module defaulted to a boolean value.
This is documented in  https://github.com/ckan/ckan/issues/3287
The "fix" looked like it worked but didn't.  regardless of the setting the value was set to the empty string.
This code doesn't work:
```javascript
this.options.env = (!(this.options.env instanceof String) || (this.options.env instanceof Boolean)) && '';
```
This code Does:
```javascript
this.options.env = (typeof this.options.env == "string" && this.options.env.length == 0) || typeof this.options.env == "boolean" ? '' : String(this.options.env)
```
I did this for the `AOI` parameter also.
The rest of the changes were simply setting, naming and passing default settings to the module.
I also updated the README.md to reflect this.
=> bug fix and parameterize defaults for edc_pow.js module

ckanext/bcgov/fanstatic/edc_pow.js
line 150 is the important one: if the resource is restricted to `Government`, use the secure `OFI` regardless of whether there is a logged in user.
=> fix logic bug

ckanext/bcgov/util/helpers.py
This chunk of code was using old ofi_config settings that are no longer valid.
This was causing an error in TEST when attempting to add an OFI resourse: the delivery OFI API was being called.
=> correct ofi_config settings usage

ckanext/bcgov/fanstatic/edc_pow.js
`download_audience` can be:
`Public`
`Government`
`Name users`
If `download_audience` is `Public` set `secureSite` to `False`
Everything else sets it to `True`
=> logic fix for Named User download_audience

ckanext/bcgov/templates/base.html
It was necessary to activate the snowplow snippet in TEST, so that the GDX team could assert their changes worked.
This change de-activates this snipped in TEST.
The snipped will only be activated in PROD.
=> set logic PROD only

requirements.txt
In this change, I reference the latest version of schema. This changes the `notes` field to `description` for groups and organizations.
=> Update schema for bcgov/ckan-ui#495

ckanext/bcgov/plugin.py
To benefit from some of the newer features of the edismax query parser, I've set it to the default for incoming searches.
https://stackoverflow.com/questions/13601853/what-is-the-difference-between-dismax-and-edismax
=> Switched to edismax for search

ckanext/bcgov/plugin.py
Although the syntax is a little bit awkward, it is possible to pass a field list to package_search. Currently, an error is thrown due to some code that assumes the `group` key is present in each search result. This fixes that error so the following API call can work:
/api/3/action/package_search?q=&fl=name&fl=name
=> Fix error when package_search is used with field list

ckanext/bcgov/logic/action.py
In the latest update, I erroneously filtered out organizations that were both suborgs AND parent orgs, like WorkSafeBC. Additionally, I filtered out sub-organizations with 0 datasets. This update includes such organizations to better conform to legacy behaviour.
=> Updated organization_list_related to better match prior behaviour

ckanext/bcgov/logic/action.py
Refactored organization_list_related to build hierarchy in a flat list directly instead of going through the unneeded intermediary step wherein a tree structure is built.
=> Refactored organization_list_related

ckanext/bcgov/logic/action.py, ckanext/bcgov/plugin.py
Added an API endpoint `/api/3/action/whoami` to identify the currently logged in user. This is so the UI doesn't have to use heuristics to [extract that id from activity feed information](https://github.com/bcgov/ckan-ui/blob/eb92f8aca0bd254254ce185113cd56140fadcc9d/frontend/src/components/pages/user.vue#L77:L86).
=> Added whoami endpoint
