- ckanext/bcgov/templates/package/read.html
Always show for owners and sysadmins
Show only when data present for other users
> show lineage+quality metadata

- ckanext/bcgov/plugin.py
Fixes a typo for the location of the Disqus controller.
> Fixing issue with Disqus and controller location

- .gitignore
- ckanext/bcgov/commands/edc_commands.py
Just some minor things in preparation for migrating to CKAN 2.3
- Add a .gitignore
- Document setup commands
- Get rid of hardcoded relative paths
- Fix creating vocabularies
> Refactorings

- ckanext/bcgov/commands/edc_commands.py
- ckanext/bcgov/controllers/api.py
- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/edc_theme.css
- ckanext/bcgov/forms/dataset_form.py
- ckanext/bcgov/forms/validators.py
- ckanext/bcgov/logic/action.py
- ckanext/bcgov/templates/package/resource_edit.html
- ckanext/bcgov/templates/user/read.html
- ckanext/bcgov/templates/user/read_base.html
- ckanext/bcgov/util/helpers.py
- pip-requirements.txt
Fixes a number of issues related to migrating to CKAN 2.3
> Migration2.3

- ckanext/bcgov/fanstatic/edc_schema.css
- ckanext/bcgov/templates/package/snippets/map_view.html
- ckanext/bcgov/templates/package/snippets/resource_view.html
- ckanext/bcgov/templates/user/dashboard.html
- ckanext/bcgov/templates/user/dashboard_unpublished.html
Resolving of various issues for release 1.1.0
> Issues for 1.1.0

- ckanext/bcgov/fanstatic/edc_theme.css
- ckanext/bcgov/fanstatic/responsive.css
- ckanext/bcgov/fanstatic/responsive.js
- ckanext/bcgov/templates/base.html
- ckanext/bcgov/templates/header.html
- ckanext/bcgov/templates/package/snippets/package_basic_fields.html
- ckanext/bcgov/templates/package/snippets/package_metadata_fields.html
The 6 commits solves the following JIRA tickets from top to bottom:
CITZEDC-740: Remove the Search box in the header
CITZEDC-719: Move lineage and Data quality fields higher up
CITZEDC-750: Details href from Datastore Upload log has incorrect reference 
CITZEDC-614: add object name to geographical extent section for suppliers
CITZEDC-722: responsiveness not working properly at record level
CITZEDC-754: mixed content errors associated with https implementation
> updates on some JIRA tickets

- ckanext/bcgov/fanstatic/responsive.css
Explore button are displayed now when window size is smaller than 768px.
> CITZEDC-722 responsiveness on record-level page

- ckanext/bcgov/scripts/export/dataset_export.py
- ckanext/bcgov/scripts/export/run_exporter.py
- ckanext/bcgov/scripts/export/update_datastore_content.py
added arguments to script to run from delivery, test or production.
> updated exporter to run from any env

- setup.py
Changed required ckan version number to 2.3.3 in setup.py
> CITZEDC794 - Review 2.3 patch release for incorporation into v1.2.1

- ckanext/bcgov/scripts/data/edc-vocabs.json
Please check to see if this was done correctly.
> added N/A as an option for non-geographic resources

- ckanext/bcgov/scripts/export/columns.json
- ckanext/bcgov/scripts/export/dataset_export.py
- ckanext/bcgov/scripts/export/exporter.py
The object name of geographic datasets has been added to the geographic resource following a request from users.
> added object name to geographic ouput

- ckanext/bcgov/templates/package/snippets/map_view.html
Button text now reads 'View in iMapBC'
> CITZEDC-844 - Change iMap link to iMapBC

- ckanext/bcgov/logic/action.py
Changed the query for getting members of the orginzation to only get
members that have the state 'active'.
> CITZEDC-843 - Email notfications being sent to removed users

- ckanext/bcgov/fanstatic/edc_resource.js
- ckanext/bcgov/fanstatic/edc_theme.css
- ckanext/bcgov/templates/package/snippets/resource_form.html
Resovles #99
Simple CSS spinner and element to cover the form once the user clicks on
the Add button to submit the resource.
> Add a spinner to add resource form

- CHANGELOG.md
- ckanext/bcgov/version.py
Also updated ext version number
Issue #121 
@ll911 steps 2-4 are for the build env, steps 5-7 are done on the server
> Included steps for 2.5.2 upgrade

- ckanext/bcgov/fanstatic/edc_theme.css
https://github.com/bcgov/ckanext-bcgov/issues/99
> Moved the spinner to the bottom of the form

- ckanext/bcgov/templates/package/auth_error.html
Changed the message to let users know that they should log in if they're
challenged with an unauthorization page
> Issue #79 - Reminder to login if unauthorized

- ckanext/bcgov/fanstatic/edc_gov.css
- ckanext/bcgov/fanstatic/edc_theme.css
Fixes #115 
This bug also affects other browsers too.
> Issue #115 - layout bug in iPhone 5

- ckanext/bcgov/templates/package/snippets/package_metadata_fields.html
Fixes #149 
Removed the image upload from the web UI.
> Removed image upload for packages

- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/forms/edc_datasets.py
- ckanext/bcgov/templates/package/snippets/resource_extra_fields.html
The schema had to be updated to allow for Resource Storage Location to not be required for adding/editing resources, hopefully these modifications don't cause any problems with existing resources with a set resource storage location field
> Issue #148 - Remove Resource Storage Location from UI

- ckanext/bcgov/fanstatic/edc_theme.css
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/package/resource_read.html
- ckanext/bcgov/templates/package/snippets/resource_item.html
- ckanext/bcgov/util/helpers.py
Resources that are uploaded now display the size and mimetype of the upload on dataset and resource views
This is possible due to bcgov/ckan#4
^ will be in core ckan in the future
> Issue 119 size mimetype

- ckanext/bcgov/templates/package/resource_read.html
Issue #117 
Resource Last Modified now dipslay in Additional Information on a
resource page
> Issue #117 - Display Resource Last Modified time

- ckanext/bcgov/templates/package/snippets/resource_item.html
> Issue #119 - Remove () when there's no size

- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/organization/edit_base.html
- ckanext/bcgov/templates/organization/members.html
- ckanext/bcgov/templates/organization/read_base.html
Also checking user for edit permissions on the viewing organization
Currently displaying all user part of the org
> Issue #155 - Member list of Organizaitons

- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/edc_gov.js
- ckanext/bcgov/fanstatic/ofi/ofi_lookup.js
- ckanext/bcgov/fanstatic/ofi/ofi_style.css
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/package/new_resource.html
Test code for ofi lookup with object name in ckan.
Geographic Datasets with an object name, when adding/editing a resource for the dataset, will have a modal pop up and automatically call ofi to check to see if the object is available to the user. 
How this works is the api call to https://delivery.apps.gov.bc.ca/pub/dwds-ofi will use whatever cookie that the browser already has in storage for the .apps.gov.bc.ca domain.
An issue that may arise is CORS being blocked due to access-control-allow-origin. This is a problem for our local env, this issue may not arise in cad. That is what this PR is to test for.
> Ofi prototype

- ckanext/bcgov/templates/package/new_resource_not_draft.html
- ckanext/bcgov/templates/package/snippets/ofi_lookup.html
forgot to add these templates to #178 PR
> Ofi proto missing templates

- ckanext/bcgov/templates/package/snippets/additional_info.html
Issue #176 
Adjusted the field column size to be smaller.
> Adjusted the width for data and lineage column

- ckanext/bcgov/version.py
Reason due to critical bugs in prod
> Changing ext release number to 1.5.2

- ckanext/bcgov/fanstatic/ofi/ofi_lookup.js
- ckanext/bcgov/templates/package/new_resource.html
- ckanext/bcgov/templates/package/new_resource_not_draft.html
Reason is to accelerate the release schedule due to critical bugs.
> Commenting out ofi prototype code

- ckanext/bcgov/scripts/data/edc-vocabs.json
new projection will be added in 1.6
> removed new bc albers projection

- ckanext/bcgov/fanstatic/ofi/ofi_lookup.js
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/package/new_resource.html
- ckanext/bcgov/templates/package/new_resource_not_draft.html
- ckanext/bcgov/templates/package/snippets/ofi_lookup.html
- ckanext/bcgov/templates/package/snippets/resource_form.html
- ckanext/bcgov/util/helpers.py
re-enabling ofi prototype for testing in cad
> Ofi proto, re-enable for testing

- ckanext/bcgov/controllers/api.py
- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/fanstatic/ofi/ofi_lookup.js
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/ofi/ofi_test.html
> New OFI controller in ext, testing user cookie

- ckanext/bcgov/logic/action.py
> Adding checks for user and member state

- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/package/new_resource.html
- ckanext/bcgov/templates/package/new_resource_not_draft.html
- ckanext/bcgov/templates/package/snippets/resource_form.html
Sorry for the confusion, removing ofi stuff
> Remove ofi for 1.5.3 release

- ckanext/bcgov/templates/package/resource_read.html
- ckanext/bcgov/templates/package/snippets/resource_item.html
Applies UI updates for issue #210 .
> #210 - Updating resource list and read screens

- ckanext/bcgov/templates/organization/edit_base.html
> Changed breadcrumb text to Edit for org edit view

- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/ofi/ofi_lookup.js
- ckanext/bcgov/fanstatic/ofi/ofi_style.css
- ckanext/bcgov/logic/auth/ofi/call_action.py
- ckanext/bcgov/logic/ofi/__init__.py
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/ofi/snippets/geo_resource_form.html
- ckanext/bcgov/templates/ofi/snippets/populate_failed.html
- ckanext/bcgov/templates/ofi/snippets/populate_success.html
- ckanext/bcgov/templates/package/new_resource.html
- ckanext/bcgov/templates/package/new_resource_not_draft.html
- ckanext/bcgov/templates/package/snippets/ofi_lookup.html
- ckanext/bcgov/templates/package/snippets/resource_form.html
- ckanext/bcgov/util/helpers.py
Issue #213 
Base OFI api in ckan
> Ofi - Adding OFI Resources

- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/ofi/ofi_lookup.js
- ckanext/bcgov/logic/ofi/__init__.py
> Ofi - Make all ofi calls secure

- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/ofi/ofi_lookup.js
- ckanext/bcgov/forms/edc_datasets.py
- ckanext/bcgov/logic/auth/ofi/call_action.py
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/templates/package/snippets/ofi_lookup.html
also adding `ofi` metadata field to resource schema for Geographic Datasets
> Adding auth check for adding ofi resources

- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/fanstatic/ofi/ofi_modal.js
- ckanext/bcgov/fanstatic/ofi/ofi_style.css
- ckanext/bcgov/logic/auth/ofi/call_action.py
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/ofi/ofi_test.html
- ckanext/bcgov/templates/package/new_resource.html
- ckanext/bcgov/templates/package/new_resource_not_draft.html
- ckanext/bcgov/templates/package/snippets/ofi_modal.html
Issue #213 
Also various changes to the modal and refactoring
> Ofi - Adding remove ofi resources to modal

- ckanext/bcgov/fanstatic/ofi/ofi_modal.js
> Front-end display for succesful removal of ofi resources

- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/ofi/ofi_modal.js
- ckanext/bcgov/logic/auth/ofi/call_action.py
- ckanext/bcgov/logic/ofi/__init__.py
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/ofi/snippets/geo_resource_form.html
- ckanext/bcgov/templates/ofi/snippets/populate_success.html
- ckanext/bcgov/templates/package/resources.html
- ckanext/bcgov/templates/package/snippets/resource_item.html
- ckanext/bcgov/util/helpers.py
dataset resource page for managing resources is broken/not finished yet
> Adding edit ofi resources

- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/ofi/ofi_modal.js
and fix for datepicker on edit
> Forgot secure should be set to true for cad

- ckanext/bcgov/fanstatic/ofi/ofi_modal.js
- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/package/resources.html
- ckanext/bcgov/templates/package/snippets/resource_form.html
> Ofi workflow for modal controls

- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/edc_mow.js
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/snippets/edc_mow.html
adding success failure messages for create order call
> Ofi proto/ issue 212

- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/fanstatic/edc_mow.js
- ckanext/bcgov/logic/ofi/__init__.py
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/templates/snippets/edc_mow.html
debug messages added for create order calls
https is now used for leaflet map requests
> Emails now are validated

- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/fanstatic/edc_mow.js
- ckanext/bcgov/fanstatic/ofi/ofi_modal.js
- ckanext/bcgov/fanstatic/ofi/ofi_style.css
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/ofi/snippets/geo_resource_form.html
- ckanext/bcgov/templates/package/snippets/resource_item.html
> Base setup for second call to ofi api create order

- ckanext/bcgov/fanstatic/edc_mow.js
- ckanext/bcgov/fanstatic/edc_mow_style.css
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/templates/snippets/edc_mow.html
Modal reduced height, various text changes outlined in the issue, swapped email and consent spots, email input now displays a popover.
Note* _initStart has been moved out of the shown.bs.tab event handler due to recursive other event handling within the modal via bootstrap
> #212 - Various UI fixes

- ckanext/bcgov/fanstatic/edc_mow_style.css
- ckanext/bcgov/logic/ofi/call_action.py
> Changing ofi resource naming scheme

- ckanext/bcgov/scripts/data/edc-vocabs.json
> Adding openapi to edc vocab

- ckanext/bcgov/templates/ofi/ofi_modal.html
> Fixing typo in ofi modal

- ckanext/bcgov/logic/auth/ofi/call_action.py
Issue #293 
crs_types action now available to public users
> Issue #293 - Allowing anonymous access to crs_types action

- ckanext/bcgov/logic/auth/ofi/call_action.py
Issue #297 
Correcting the check_access calls to use id for checking the package.
> Issue #297 - Correcting check_access calls to include correct id reference

- ckanext/bcgov/templates/package/snippets/resource_form.html
changed the Manage button from 'Manage DWDS Resources' to 'Manage BCDW Resources'
> small change to trigger a pull request

- ckanext/bcgov/templates/package/snippets/additional_info.html
Added a fix for **Data Quality** and **Lineage Statement** also.
> MD fix for "Data Quality" and "Lineage Statement"

- ckanext/bcgov/plugin.py
The new rules are now specific to edc dataset types, only new geographic datasets go through
> Bug fix route that prevented accessing the new organizations view

- ckanext/bcgov/controllers/package.py
> #323 - Saving datasets without resources will be active (not edc_state)

- ckanext/bcgov/logic/ofi/call_action.py
> Issue #306 - Changing ofi resource names

- ckanext/bcgov/templates/package/snippets/resource_item.html
I made changes and pushed them strait on to master.  This is a feature branch to initiate a pull request, merge and build trigger.
> minor change to trigger build

- ckanext/bcgov/templates/package/snippets/resource_item.html
- ckanext/bcgov/util/helpers.py
> fix case where () appear for external linked resources

- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/package/resources.html
Quick fix to change `OFI` to `BCGW` on button and MOW
> issue #343 change OFI to BCGW

- ckanext/bcgov/templates/package/resource_read.html
Issue #338 
Url has been removed for ofi resources
> Issue #338 - Removing url for ofi resources

- setup.py
Issue #339
Need to allow the extension to use this version of our ckan
> Issue #339 - Updating ckan version to 2.5.5-bcgov

- ckanext/bcgov/version.py
> Update version.py to 1.6.6

- README.md
trigger a build as code in[ bcgov/ckan](https://github.com/bcgov/ckan) was changed.
> trigger a build of DLV

- ckanext/bcgov/fanstatic/edc_pow.js
- ckanext/bcgov/templates/snippets/edc_mow.html
* Added a `div` to `edc_mow.html` 
* Added (coppied for now) `edc_mow.js` to `edc_pow.js` and modified it so that it is its own module.
* `edc_pow.js` simply opens a context window for `#edc_pow` content
> Pow mow demo

- ckanext/bcgov/templates/snippets/debug.html
i didnt realize this wasn't in the last pr
> Adding missing debug template

- ckanext/bcgov/logic/ofi/__init__.py
#409 need to test in cad due to it not being testable locally
> #409 - Handling ofi api call exceptions

- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/logic/ofi/__init__.py
- ckanext/bcgov/logic/ofi/call_action.py
Need to see how cad handles this error, cant really test in local env
> #409 - Raising the ofi service error to the package controller level

- ckanext/bcgov/controllers/ofi.py
- ckanext/bcgov/fanstatic/edc_mow.js
- ckanext/bcgov/logic/ofi/__init__.py
Hopefully this is the last PR for this issue
> #409 - Added ofi service error messages to ajax error callback

- ckanext/bcgov/fanstatic/edc_pow.js
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/package/snippets/resource_item.html
- ckanext/bcgov/templates/package/snippets/resources_list.html
- ckanext/bcgov/templates/snippets/edc_mow.html
- ckanext/bcgov/util/helpers.py
This version of the pow for ckan has been modified (sorry Dave) for CAD testing, all the OFI resource downloads now initiate the POW instead of the MOW. Config options have also been added to CAD's ini.
> #401 - Implement POW

- ckanext/bcgov/plugin.py
Reverts bcgov/ckanext-bcgov#455
> Revert "switch q.op syntax to make fq files mandatory"

- ckanext/bcgov/plugin.py
Reverts bcgov/ckanext-bcgov#454
> Revert "A better solution to the Filter Query issue"

- ckanext/bcgov/plugin.py
Reverts bcgov/ckanext-bcgov#453
> Revert "amend fix for facet"

- ckanext/bcgov/plugin.py
Reverts bcgov/ckanext-bcgov#452
> Revert "fix facet syntax with 'AND'"

- ckanext/bcgov/controllers/package.py
- ckanext/bcgov/fanstatic/ofi/ofi_modal.js
- ckanext/bcgov/logic/ofi/call_action.py
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/ofi/snippets/geo_resource_form.html
- ckanext/bcgov/templates/ofi/snippets/populate_success.html
- ckanext/bcgov/templates/package/read.html
- ckanext/bcgov/templates/package/resource_read.html
- ckanext/bcgov/templates/package/snippets/resource_item.html
- ckanext/bcgov/templates/package/snippets/resources_list.html
- ckanext/bcgov/util/helpers.py
#401 
Ofi api now only handles a single ofi resource.
However, other parts of the code base need to keep certain legacy parts of handling multiple ofi resources, such as templates and view loading.
> #401 - Single POW OFI resource

- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/macros/tracking.html
- ckanext/bcgov/templates/ofi/ofi_modal.html
- ckanext/bcgov/templates/package/read.html
- ckanext/bcgov/templates/package/resource_read.html
- ckanext/bcgov/templates/package/snippets/resource_extra_fields.html
- ckanext/bcgov/util/helpers.py
#403 
Fixed tracking display on resource view
#375 
Fixed default option when no projection has been selected
> 403 & 375 - View count and revert default projection value

- ckanext/bcgov/scripts/data/edc-vocabs.json
- ckanext/bcgov/scripts/edc_tags.py
- requirements.txt
#395 
Updating edc resource-storage-location vocabulary list, also made a new script for updating vocabulary lists, the old scripts are in need of updating.
> 395 - Updated list, included edc_tag script for updating list

- ckanext/bcgov/scripts/delete_vocabs.py
- ckanext/bcgov/scripts/edc_tags.py
#395 
Completed the edc_tags script.
> 395 - Updated edc_tags.py script tool for updating, creating and deleting

- ckanext/bcgov/templates/snippets/package_item.html
> #472 - Removed last modified display on package list items

- ckanext/bcgov/templates/snippets/main-navigation.html
- ckanext/bcgov/templates/snippets/mobile-main-navigation.html
#474 
Removed the Data Catalogue link and replaced it with Dataset Usage
> #474 - Added dataset usage link to the navigation bar

- ckanext/bcgov/commands/edc_commands.py
- ckanext/bcgov/fanstatic/edc_pow.js
- ckanext/bcgov/scripts/base.py
- ckanext/bcgov/scripts/create_orgs.py
- ckanext/bcgov/scripts/edc_tags.py
- ckanext/bcgov/templates/package/snippets/resource_extra_fields.html
`paster --plugin=ckanext-bcgov edc_command create-all-orgs` has been rewritten to work now with the `org_suborg_sector_mapping_forEDC.csv`. This cmd is used with the new dev env
> Fixed edc_command for creating orgs, pip8 fixes to scripts

- .github/ISSUE_TEMPLATE/user_story.md
- .github/issue_template.md
This is to setup a template for test cases and user stories (for feature requests)
> Add TESTCASE and USER STORY templates

- ckanext/bcgov/templates/user/dashboard.html
This is just a quick demonstration of a button to start the ARGG API Registration tool.
> added button for ARGG

- ckanext/bcgov/templates/package/resource_read.html
- ckanext/bcgov/templates/snippets/edc_mow.html
`edc_mow.html` - This does not appear to be use.  `resource_read.html` is the correct location for the test.
> test for authenticated user in correct place

- ckanext/bcgov/templates/package/resource_read.html
I had use `%` when I should have used `#` for JINJA comments.
> fixed typographic error

- ckanext/bcgov/fanstatic/edc_pow.js
change passed parameters to boolean values.  
The incorrect type was causing the POW to fail.
> fix logic bug

- ckanext/bcgov/templates/base.html
This is to enable snowplow analytics
> add snowplow snippet

- .github/issue_template.md
- ckanext/bcgov/templates/base.html
This is so that when a new issue is created in the repository, the **User Story** template (A standard form and a table form) are provided, in addition to the usual **TEST CASE** template.
Users are free to delete anything they don't want to use.
> Update to issue template

- .github/issue_template.md
- README.md
- ckanext/bcgov/templates/base.html
> prepare for 1.7.13 release (#625)

- ckanext/bcgov/templates/base.html
I spoke with Ryan Janes about this.
He stated their testing is complete and we can remove the snippet form all environments.
> remove snowplow snippet

- ckanext/bcgov/fanstatic/edc_pow.js
tabs are problematic.
I switched ts => 2sp
> switch tabs for spaces

- ckanext/bcgov/templates/base.html
Ryan Janes requested that we update the snowplow snippet.
This PR updates the snippet.
It also changes the logic to test that the snippet works correctly in test.
An additional change will be required to "hide" the snippet in TST and activate it in PROD.
> updated snowplow snippet & tmp logic change

- ckanext/bcgov/templates/package/snippets/package_form.html
> Ckanext bcgov 687

- ckanext/bcgov/templates/package/read.html
Trivial change to button's label.
> #595 - Permalink button appears to do nothing

- ckanext/bcgov/templates/package/snippets/package_form.html
Reverted a couple of commits because previous behaviour is preferred
> Ckanext bcgov 681

- requirements.txt
prepare master req for bcdc based on ckan-2.7.2 core
> Update requirements.txt for bcdc base on ckan-2.7.2 core

- ckanext/bcgov/fanstatic/edc_restrict_browser.js
Changed text of warning message.
> #698 - Custom download does not launch in IE 11

- requirements.txt
Tested code change for "get_espg_id" method.  Tests passed in CATI.
> Merge dev to master

- ckanext/bcgov/logic/action.py
- ckanext/bcgov/logic/get.py
- ckanext/bcgov/plugin.py
- ckanext/bcgov/templates/group/snippets/info.html
Merging to master directly because dev is currently in an unmergable state
> Ckanext bcgov775 hidden groups

- .github/workflows/dev_pull_closed.yml
- .github/workflows/workflow.yml
- codecov.yml
added workflow file to call bot on push, updated workflow for sonar/codecove to run on pr open, added condecov.yml to root of repo
> added workflows for bot and sonar/codecov

- requirements.txt
https://proj.data.gov.bc.ca/jira/browse/DDM-1655
> revert Werkzeug back to 0.11.10

- ckanext/bcgov/templates/package/snippets/map_view.html
- Modified the code that is used in the map preview iframe
- Now references SMK site bcdc-smk.data.gov.bc.ca
- Changes implemented for parameterization for SMK map call
- This is the change that we want to put into prod later today
> Change DMF based map preview to SMK

- requirements.txt
Update github.com/bcgov/ckanext-bcgov-schema commit hash to latest.
> Update schema commit

- ckanext/bcgov/logic/auth/get.py
- ckanext/bcgov/plugin.py
- ckanext/bcgov/util/util.py
Includes update to use edismax by default for incoming searches, and improvements to group search logic.
> Migrate dev to test

- ckanext/bcgov/logic/action.py
Reverts bcgov/ckanext-bcgov#910
> Revert "Changed log level because dev wasn't showing log lines"

- ckanext/bcgov/logic/action.py
Reverts bcgov/ckanext-bcgov#909
> Revert "Added logging to determine source of error"

- ckanext/bcgov/logic/action.py
Reverts bcgov/ckanext-bcgov#906
> Revert "Updated email notification template and added parent org admins/edito…"

- ckanext/bcgov/controllers/site_map.py
Reverts bcgov/ckanext-bcgov#916
> Revert "Uncomment sitemap caching"

- requirements.txt
Update git hash to latest master hash
> Update sso git hash

- requirements.txt
Rough update of requirements for ckan 2.8 along with update to ckan 2.8.0
> Update requirements to ckan 2.8.0

- requirements.txt
- removes unneeded pluggins
- update schema
> Migrate requirement changes to main

- requirements-py2.txt
Undo changes as they appear to prevent permanent pip install
> Revert "Update requirements-py2.txt"
